### ISSUE TITLE
No images loading. Everything keeps spooling

### ISSUE THREAD

**Issue by Phtephent** [chilli-axe/mpc-autofill#225] opened 2024-03-23 23:29 UTC
# System

- **Operating System (including version)**: 10 
- **Desktop Tool Version**:
- **Browser (including version)**: Chrome

# Affected Components

- [ ] Backend
- [ ] Frontend
- [ ] Desktop Tool

# Description

When I go to the website it never let's me submit the images. When it does, I get a syntax error, after that the submit button is able to be clicked and then nothing happens.
![MPC Syntax Bug](https://github.com/chilli-axe/mpc-autofill/assets/164695079/746ab088-bb50-437a-aeb6-db30e9aeafce)
![MPCBug](https://github.com/chilli-axe/mpc-autofill/assets/164695079/83fa4d15-94bc-46bd-bf58-e1795bd03136)

# Steps to Reproduce

I have no idea how to reproduce this. It could be on my end, but I have no idea

-

**Comment by CrisperDarkling** [comment] 2024-03-26 00:57
Same here, it seems to get some of the basic xml info like card amounts and names, but that's about it
<img width="357" alt="image" src="https://github.com/chilli-axe/mpc-autofill/assets/31858086/d6791c70-ac2c-478b-a307-15908d45db39">
![image](https://github.com/chilli-axe/mpc-autofill/assets/31858086/6573951f-823b-4075-8758-15e91e6b0057)

**Comment by ndepaola** [comment] 2024-03-26 04:42
apologies for the inconvenience here - this was related to some difficulties we experienced on the VPS the https://mpcfill.com server is running on. it should all be cleared now, thanks for your patience!

(for those following at home - this is a duplicate of #226 and #228)

**Closed by ndepaola** 2024-03-26 04:42 UTC
