### ISSUE TITLE
mpcfill beta - Card backside doesn't load with partial frontside name

### ISSUE THREAD

**Issue by bwsinger** [chilli-axe/mpc-autofill#165] opened 2023-08-16 19:44 UTC
# System

- **Browser (including version)**: Chrome Version 115.0.5790.114

# Affected Components

- [X] Backend

# Description

When using Fuzzy search and a partial card name is used, if the resulting best match is a double sided card the backside will not be queried. If the full name of the front side of a double sided card is queried, then the backside will be queried.

# Steps to Reproduce

**Server URL**:  https://mpcfill.com
**Card Text Query**: 
```
Birgi
Birgi, God of Storytelling
```
**Video Demo**:
![mpcfill-bug2](https://github.com/chilli-axe/mpc-autofill/assets/16724046/ddf6a839-862f-47da-b543-5fd3f754a398)

**Comment by ndepaola** [comment] 2023-08-16 23:32
this is the expected behaviour at present because we match the front query to a DFC pair before querying anything from the backend, so your search settings don't factor into it at all - but i agree that it should work the way you expect - just hadn't really considered what people would expect to happen in the fuzzy search case. thanks for raising this, i'll address this and close the issue when it's done :) fwiw this is purely related to the frontend

**Closed** 2023-08-17 12:22 UTC
Labels: beta feedback

**Comment by ndepaola** [comment] 2023-08-17 13:08
this has been addressed - if you have fuzzy search turned on, the frontend will now associate your query with a DFC pair if a pair's front name starts with your query. if it's ambiguous - i.e. two or more DFC pair front names start with your query - no match will be made.
