### ISSUE TITLE
Script failure after downloading of images

### ISSUE THREAD

**Issue by johtso** [chilli-axe/mpc-autofill#56] opened 2021-12-05 19:27 UTC
```traceback
Traceback (most recent call last):
  File "autofill.py", line 501, in <module>
  File "autofill.py", line 144, in fill_cards
  File "selenium/webdriver/remote/webdriver.py", line 636, in execute_script
  File "selenium/webdriver/remote/webdriver.py", line 321, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 242, in check_response
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot set properties of null (setting 'value')
  (Session info: chrome=96.0.4664.55)

[8568] Failed to execute script autofill
```

Running fine after restarting the script.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/830800/144760661-2d4514b5-f582-4530-898c-f07a80898620.png">

**Comment by MrTeferi** [comment] 2022-02-24 09:10
Yeah just rerun the script and don't mess with the chrome window till it gets going I find this usually happens when I disrupt or interact with the window somehow when its firing up.

**Comment by ndepaola** [comment] 2022-09-02 03:17
duplicate of https://github.com/chilli-axe/mpc-autofill/issues/52

**Closed by ndepaola** 2022-09-02 03:17 UTC
Labels: bug
