### ISSUE TITLE
Unknown Error: Unhandled Inspector Error

### ISSUE THREAD

**Issue by MeMental** [chilli-axe/mpc-autofill#141] opened 2023-05-06 12:19 UTC
Hi,
i´ve been trying to upload my XML for 4 Days now and I keep running into the same error... I´ve tried to see if it´s related to a single card or picture but that does not seem to be the case since the error just comes up randomly while the programm is running. I have no given the XML to a friend to upload it trying to hopefully circumvent the problem until I have a workaround or it´s fixed... 
Things i´ve tried:
Clearing the Folder with the .exe
Redownloading the .exe
Changing the XML so that different IDs for the same Picture no longer lead to failed uploads
Creating new XMLs
![error message](https://user-images.githubusercontent.com/132756137/236623585-09359cac-792e-4a27-9ca9-1a06d811217d.PNG)
![dshh](https://user-images.githubusercontent.com/132756137/236623596-cf63b15d-d32e-4c90-9cd6-baefa595c7f2.PNG)
![asfs](https://user-images.githubusercontent.com/132756137/236623597-8765922a-1213-48ca-8d92-08960847a30b.PNG)

**Comment by ndepaola** [comment] 2023-05-07 21:41
hey there - i'm sorry to hear this issue is preventing the tool from working properly for you! i believe i've identified a fix, just need to test it some more before putting out a new release.

**Comment by ndepaola** [comment] 2023-05-08 07:00
the issue is fixed by this release https://github.com/chilli-axe/mpc-autofill/releases/tag/v4.2.5 please reopen this thread if it persists for you

**Closed by ndepaola** 2023-05-08 07:00 UTC
Labels: bug
