### ISSUE TITLE
Linux "no such driver version" error

### ISSUE THREAD

**Issue by Henelik** [chilli-axe/mpc-autofill#185] opened 2023-09-28 02:09 UTC
# System

- **Operating System (including version)**: Linux Mint 21.2 Cinnamon
- **Desktop Tool Version**: [v4.3.2](https://github.com/chilli-axe/mpc-autofill/tree/v4.3.2)
- **Browser (including version)**: Brave 1.58.131

# Affected Components

- [ ] Backend
- [ ] Frontend
- [x] Desktop Tool

# Description

Error message:
```
An uncaught exception occurred:
No such driver version 117.1.58.131 for linux64
```

Tool immediately aborts.

# Steps to Reproduce

Run the desktop tool.

**Comment by ndepaola** [comment] 2023-09-28 23:17
closed as duplicate of #168

**Closed by ndepaola** 2023-09-28 23:17 UTC
