### ISSUE TITLE
Using --skipsetup fails shortly after pressing Enter

### ISSUE THREAD

**Issue by DagonX** [chilli-axe/mpc-autofill#118] opened 2023-02-05 00:49 UTC
I keep getting the following exception when trying to continue an existing project. Sometimes it will go through, but 9 times out of 10 it will crash right after I've:

1. logged in
2. opened the project
3. navigated to Customize Front
4. reloaded until all images are properly loaded
5. opened the Change Layout dialogue a few times so that is preloaded as well
6. returned to console and hit enter

It usually throws the following error:

> An uncaught exception occurred: Message: javascript error: displayTotalCount is not defined
>   (Session info: chrome=109.0.5414.120)
> Stacktrace:
> Backtrace:
>         (No symbol) [0x00766643]
>         (No symbol) [0x006FBE21]
>         (No symbol) [0x005FDA9D]
>         (No symbol) [0x006009E4]
>         (No symbol) [0x006008AD]
>         (No symbol) [0x006012E5]
>         (No symbol) [0x006679F7]
>         (No symbol) [0x0064FD7C]
>         (No symbol) [0x00666B09]
>         (No symbol) [0x0064FB76]
>         (No symbol) [0x006249C1]
>         (No symbol) [0x00625E5D]
>         GetHandleVerifier [0x009DA142+2497106]
>         GetHandleVerifier [0x00A085D3+2686691]
>         GetHandleVerifier [0x00A0BB9C+2700460]
>         GetHandleVerifier [0x00813B10+635936]
>         (No symbol) [0x00704A1F]
>         (No symbol) [0x0070A418]
>         (No symbol) [0x0070A505]
>         (No symbol) [0x0071508B]
>         BaseThreadInitThunk [0x770FF989+25]
>         RtlGetAppContainerNamedObjectPath [0x77505DE4+228]
>         RtlGetAppContainerNamedObjectPath [0x77505DB4+180]

Hope this helps.

**Comment by Hauwkeee** [comment] 2023-02-09 07:40
Same here :-/

**Comment by ndepaola** [comment] 2023-03-05 03:17
closing as a duplicate of #71

**Closed by ndepaola** 2023-03-05 03:17 UTC
