### ISSUE TITLE
Image Upload Freeze

### ISSUE THREAD

**Issue by SkyNuetz** [chilli-axe/mpc-autofill#245] opened 2024-07-03 19:33 UTC
# System

- **Operating System (including version)**: IOS macOS Sonoma version 14.5
- **Desktop Tool Version**: v4.5.1
- **Browser (including version)**: chrome

# Affected Components

- [ ] Backend
- [ ] Frontend
- [ x ] Desktop Tool

# Description

 

<img width="814" alt="Screenshot 2024-07-03 at 2 22 01 PM" src="https://github.com/chilli-axe/mpc-autofill/assets/174575294/a6a359be-ca6c-4272-bdf4-fbd71fa2f09e">
[autofill_crash_log.txt](https://github.com/user-attachments/files/16089976/autofill_crash_log.txt)

Not sure if the screenshot posted. Whenever I go through the process of uploading my project into makeplayingcards.com it begins to the uploaded but then it will freeze on a random image and will populate an error. I have screenshot the error.
-

# Steps to Reproduce

 make a project on MPC fill and then download and move to desktop. Activate the autofill macOS, and go through the steps on the program. Once going through the upload process it eventually freezes.
 It happens with any project I try to autofill. I have tried several different projects.

I could not upload the xml file but here is the deck list.

1 Arcane Denial
1 Archmage's Charm
1 Artistic Refusal
1 Avacyn, Angel of Hope
1 Badlands
1 Bala Ged Recovery
1 Bayou
1 Birds of Paradise
1 Bloodstained Mire
1 Boon of the Wish-Giver
1 Burgeoning
1 Command Tower
1 Conflux
1 Consecrated Sphinx
1 Cosmic Epiphany
1 Cruel Ultimatum
1 Cryptic Command
1 Cultivate
1 Deflecting Swat
1 Demonic Tutor
1 Dig Through Time
1 Door to Nothingness
1 Dragonlord's Prerogative
1 Entomb
1 Expropriate
1 Farseek
1 Flooded Strand
5 Forest
1 Hullbreaker Horror
1 Imperial Seal
1 Inspired Ultimatum
1 Into the Story
4 Island
1 Jin-Gitaxias, Progress Tyrant
1 Kodama's Reach
1 Lively Dirge
1 Marsh Flats
1 Misty Rainforest
1 Mnemonic Deluge
1 Mystic Confluence
1 Narset's Reversal
1 Nature's Lore
1 Naya Charm
1 Nexus of Fate
1 Omniscience
1 One with the Multiverse
1 Opportunity
1 Oriq Loremage
1 Polluted Delta
1 Precognitive Perception
1 Primal Command
1 Privileged Position
1 Progenitus
1 Rampant Growth
1 Recollect
1 Regrowth
1 Relearn
1 Reliquary Tower
1 Reshape the Earth
1 Ruinous Ultimatum
1 Rush of Knowledge
1 Sakura-Tribe Elder
1 Savannah
1 Scalding Tarn
1 Scrubland
1 Sea Gate Restoration
1 Shark Typhoon
1 Silence
1 Sink into Stupor
1 Skyshroud Claim
2 Swamp
1 Taiga
1 Teferi's Protection
1 Thousand-Year Storm
1 Three Visits
1 Tidings
1 Time Stretch
1 Timetwister
1 Tropical Island
1 Tundra
1 Underground Sea
1 Unmarked Grave
1 Vampiric Tutor
1 Vedalken Orrery
1 Verdant Catacombs
1 Vile Entomber
1 Volcanic Island
1 Waterlogged Teachings
1 Windswept Heath
1 Wooded Foothills
1 Zagoth Triome

1 Go-Shintai of Life's Origin

-

**Comment by ndepaola** [comment] 2024-07-03 23:23
iirc the `Uploading, please wait...` alert this message is reporting happens when you're partway through uploading an image and try to interact with the page, e.g. clicking anywhere on the page triggers it - though the tool will attempt to dismiss any alerts that pop up while it's doing its work.

did you happen to click on the page while an image was uploading to trigger this error? or does it happen if you start the tool and don't touch the page as it processes your order?

it sounds like two things are going on here:
* a few people have reported the MPC frontend periodically freezing - see #227 - which refreshing the page usually fixes. it sounds like you're running into the same issue
  * this isn't really a bug in the tool, but i'll look at handling these freezes in the tool when i have time
* when you tried to interact with the page while it was frozen, it popped up with this alert, which the tool didn't handle correctly
  * so i'll review our alert handling code and shore up any gaps

**Comment by SkyNuetz** [comment] 2024-07-04 01:06
This was the error when I tried to refresh. Once the program freezes I have tried waiting then I will refresh, but it stops and gives me this error. The program used to work great. Not sure what has triggered the change.

**Comment by ndepaola** [comment] 2024-07-04 02:22
hmm, i see - thanks for letting me know, i'll manually test it tonight on a medium sized order and see if i can reproduce your issues.

i re-ran our automated tests for the desktop tool and it doesn't look like they picked up any issues

more broadly - this project relies on reverse engineering the MPC frontend (as they don't have an API of any kind), so any changes they make to their frontend code can have a flow-on effect to the desktop tool

**Comment by ndepaola** [comment] 2024-08-06 09:28
howdy - i've just cut a new release https://github.com/chilli-axe/mpc-autofill/releases/tag/v4.5.2 could you try this version and see if your issue is resolved?

**Comment by ndepaola** [comment] 2024-08-09 12:25
closing this because i'm pretty sure it's the same issue as #227 and should be fixed now. pls reopen if this issue persists for you on the latest release

**Closed** 2024-08-09 12:25 UTC
