### ISSUE TITLE
An uncaught exception occurred: generator didn't yield

### ISSUE THREAD

**Issue by Quazimofo1** [chilli-axe/mpc-autofill#123] opened 2023-02-23 14:52 UTC
when running the exe everything looks top be working well untill the images downloaded operation complets and then the program fails with exception occurred: generator didn't yield

![image](https://user-images.githubusercontent.com/126178757/220941733-32303434-b636-4f9d-a681-568813788265.png)

![image](https://user-images.githubusercontent.com/126178757/220941790-7c46ddd0-0e42-4d45-8a32-75336de0aaed.png)

If I have missed where this has been talked about already I do apologize

**Comment by SylarGrey12** [comment] 2023-02-23 18:18
Having this same issue since yesterday, exactly. Downloads all images, won't move past this screen.

**Comment by madmovieguyx2** [comment] 2023-02-23 21:22
Same here

**Comment by EMTDIM** [comment] 2023-02-24 01:37
Same here, I set up an order 2 days ago with no issues, and since yesterday it's giving me this error.

**Comment by NathanielGet** [comment] 2023-02-24 19:14
I am similarly experiencing this

**Comment by goinftl** [comment] 2023-02-24 19:35
I am also experiencing this issue it started last night for me. I am on Ubunutu Budgie 22.04.02
The exports folder is not being created when the tool is run.

**Comment by ndepaola** [comment] 2023-02-25 04:22
looking into this now - I can't seem to reproduce this error on macOS with the XML files I've tried so far. could you guys (and anyone else) please provide your XML files and the operating system you're running? thanks and sorry for the inconvenience this has caused

**Comment by goinftl** [comment] 2023-02-25 05:13
https://drive.google.com/file/d/1T9mFwfxfI7xffMOane-TvpBZoFaGla2z/view?usp=sharing

Here is a Google Drive link with a copy of my .xml
OS: Ubuntu Budgie 22.04.2 LTS x86_64

**Comment by ndepaola** [comment] 2023-02-25 06:03
> https://drive.google.com/file/d/1T9mFwfxfI7xffMOane-TvpBZoFaGla2z/view?usp=sharing
> 
> Here is a Google Drive link with a copy of my .xml OS: Ubuntu Budgie 22.04.2 LTS x86_64

looks like you need to configure the file with public access

**Comment by goinftl** [comment] 2023-02-25 06:12
Done

**Comment by Derek-Devs** [comment] 2023-02-25 07:57
Hello,

Please find attached XML Files that can replicate this bug on my Windows machine.

Be advised that the files labeled "foil" will process just fine, however the ones labeled "nonfoil" will not. I hope that can help narrow down the debugging process for you.

https://drive.google.com/drive/folders/1Yd_gou87yytzgIsXtdzze-jGSXivm6Um?usp=share_link

**Comment by Quazimofo1** [comment] 2023-02-25 15:46
Hello ndepaola! 

Below is the XML file i've been running into issues with.

https://drive.google.com/file/d/15ZVCU7rbfpoeJiQ-mJ285RBiUnkk2aW7/view?usp=share_link

I'm also using chrome version  110.0.5481.105

and I'm running windows 11 I have system info below just in case as well

OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

Registered Organization:   HP
Product ID:                00342-20762-08256-AAOEM
Original Install Date:     2/9/2023, 9:17:11 AM
System Boot Time:          2/22/2023, 12:31:49 AM
System Manufacturer:       HP

System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 80 Stepping 0 AuthenticAMD ~3900 Mhz
BIOS Version:              AMI F.20, 7/26/2022
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     15,711 MB
Available Physical Memory: 6,058 MB
Virtual Memory: Max Size:  26,975 MB
Virtual Memory: Available: 11,163 MB
Virtual Memory: In Use:    15,812 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP

Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5022497
                           [02]: KB5012170
                           [03]: KB5022845
                           [04]: KB5022610
                           
Thank you so much for looking into this! I love the program!

**Comment by ndepaola** [comment] 2023-02-26 14:52
* i spent a decent bit of time trying to reproduce this across windows 10, ubuntu 22, and macos monterey using some of the XML's posted here and the test XML's in the repo
* i was unable to reproduce it reliably but did hit it a couple of times (n=20ish)
    * foil vs nonfoil made no discernible difference
* i'm fairly sure i have identified the code issue (i had set up a context manager incorrectly) but find myself unable to reliably test that my fix works
* at this stage, i'm still unsure what changed in MPC's frontend a few days ago to cause this to break for multiple people at once
* an open question to anyone in this thread - if you're hitting this error consistently and are familiar with python, could you please clone the repo, apply this patch https://github.com/chilli-axe/mpc-autofill/commit/f5212a7b5f33d8d86ab6774c7b91bfa00eca37b0, run the client (just run `autofill/autofill.py`), and let me know if this fixes the issue on your machine?
    * i'll continue testing this tomorrow, so if no one is able to help out here and if i haven't triggered the bug again, i'll merge the fix into master and create a new release

**Comment by edge929** [comment] 2023-03-03 14:18
I have the same issue. Took the latest autofill yesterday (3/2) and it successfully worked for an order of ~160 cards. Later that day I did another order of 350 cards and I started seeing this error. Windows 10 64-bit, Chrome 110.0.5481.178. No foil cards, one double-sided card, same back otherwise. I normally work in Java but I'll try to give the patch a try.

**Comment by ndepaola** [comment] 2023-03-04 09:29
will close this issue when a release has been created with the linked PR

**Comment by ndepaola** [comment] 2023-03-04 14:24
https://github.com/chilli-axe/mpc-autofill/releases/tag/v4.2.4

**Closed by ndepaola** 2023-03-04 14:24 UTC
Labels: bug
