### ISSUE TITLE
[Bug] Local files not loaded

### ISSUE THREAD

**Issue by Triquetra** [chilli-axe/mpc-autofill#67] opened 2022-05-27 17:35 UTC
On Windows 11, replacing the id field with the path to a local file causes autofill-windows to produce the following url for image download:

> https://drive.google.com/uc?id="C:\Games\MPCfill\local\Spawnwrithe Token.jpg"&export=download

Understandably this fails. When a vaild local path is detected, the program should not try to insert it into a google drive url.

**Comment by ndepaola** [comment] 2022-06-20 14:11
I think this issue was caused by not stripping quotation marks from file paths, which has now been fixed - could you try the latest release (or the release prior) and see if it works properly now?

**Comment by ndepaola** [comment] 2022-06-21 10:08
closing this for now - please don't hesitate to reopen this issue if the issue persists in the latest builds :)

**Closed by ndepaola** 2022-06-21 10:08 UTC
